[versions]
# android sdk
compileSdk = "33"
targetSdk = "33"
minSdk = "21"
# java
java = "VERSION_1_8"
jvmTarget = "1.8"
# plugin
agp = "7.4.2"
kotlin = "1.8.20"
ksp = "1.8.20-1.0.11"
hilt = "2.44"
# sdk
lifecycle = "2.6.1"
media = "1.6.0"
room = "2.5.2"
common = "1.0.0-beta09"
init = "1.1.0"
crouter = "2.4.0-beta01"

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version = "4.4.0" }
crashlytics = { id = "com.google.firebase.crashlytics", version = "2.9.5" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

[libraries]
# plugin
autoRegister = { group = "com.github.wangchenyan", name = "AutoRegister", version = "1.4.3-beta02" }
# androidx
coreKtx = { group = "androidx.core", name = "core-ktx", version = "1.10.1" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.6.1" }
activityKtx = { group = "androidx.activity", name = "activity-ktx", version = "1.7.2" }
fragmentKtx = { group = "androidx.fragment", name = "fragment-ktx", version = "1.6.1" }
material = { group = "com.google.android.material", name = "material", version = "1.9.0" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
coordinatorlayout = { group = "androidx.coordinatorlayout", name = "coordinatorlayout", version = "1.2.0" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version = "3.0.0" }
cardview = { group = "androidx.cardview", name = "cardview", version = "1.0.0" }
gridlayout = { group = "androidx.gridlayout", name = "gridlayout", version = "1.0.0" }
multidex = { group = "androidx.multidex", name = "multidex", version = "2.0.1" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version = "1.3.1" }
lifecycle-viewModel = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
lifecycle-liveData = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
media = { group = "androidx.media", name = "media", version.ref = "media" }
room = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
preference = { group = "androidx.preference", name = "preference-ktx", version = "1.2.0" }
# google
crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics-ktx", version = "18.5.0" }
analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx", version = "21.4.0" }
hilt = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
# wangchenyan
common = { group = "com.github.wangchenyan", name = "android-common", version.ref = "common" }
init-compiler = { group = "com.github.wangchenyan.init", name = "init-compiler-ksp", version.ref = "init" }
init-api = { group = "com.github.wangchenyan.init", name = "init-api", version.ref = "init" }
crouter-compiler = { group = "com.github.wangchenyan.crouter", name = "crouter-compiler", version.ref = "crouter" }
crouter-api = { group = "com.github.wangchenyan.crouter", name = "crouter-api", version.ref = "crouter" }
lrcview = { group = "com.github.wangchenyan", name = "lrcview", version = "2.2.1" }
# open source
loggingInterceptor = { group = "com.github.ihsanbal", name = "LoggingInterceptor", version = "3.1.0" }
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version = "2.1.0" }
glide = { group = "com.github.bumptech.glide", name = "glide", version = "4.13.2" }
zbar = { group = "cn.bertsir.zbarLibary", name = "zbarlibary", version = "1.4.2" }
blurry = { group = "jp.wasabeef", name = "blurry", version = "4.0.1" }
